apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-data
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true