apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: create-db-script
  namespace: demo-db
spec:
  managedVersions: true
  continueOnError: false
  scripts:
  - name: create-demo-database
    script: |
      CREATE DATABASE demo WITH OWNER postgres;
